### ISSUE TITLE
Watching stops working after adding this plugin

### ISSUE THREAD

**Issue by prantlf** [2wce/rollup-plugin-sourcemaps2#59]
**Describe the bug**

Watching source file appears to stop working, once this plugin is enabled.

The [rollup 4 migration guide](https://rollupjs.org/migration/#changes-to-the-plugin-api) mentions:

> Another important change is that Rollup watch mode will no longer watch ids of files that have been loaded via a plugin [load](https://rollupjs.org/plugin-development/#load) hook. So this mainly affects "virtual" files, where it really does not make sense to watch a hard drive location for changes. Instead, it is now up to plugins that use a load hook to manually call [this.addWatchFile()](https://rollupjs.org/plugin-development/#this-addwatchfile) for all the files they depend on to handle the load hook.

This plugin should be updated to call `addWatchFile` in the `load` method.

**To Reproduce**

Run `rollup -cw` and try modifying sources. The project rebuild won't kick in.

**Expected behavior**

When a source file is modified, the output has to be rebuilt automatically, if rollup is launched in the watch mode.

## Environment

- **Package Version**: 0.3.0
- **Node.js Version**: 20.15.1
- **NPM Version**: 10.7.0
- **Operating System**: macOS Sonoma 14.5 (23F79)

**Comment by 2wce** [comment]
thank you @prantlf for reporting this, i've pushed a fix in the new version let me know if this unblocks you
